language: php
php:
    # - '5.4'
    - '7.1'

script:
    - composer require cakephp/cakephp-codesniffer:dev-master
    - chmod +x vendor/bin/phpcs
    - vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests ./config
